### ISSUE TITLE
ValueError: invalid literal for int() with base 10: b''

### ISSUE THREAD

**Issue by Lijuming33** [threaTrace-detector/threaTrace#15]
scripts/test_streamspot.py >>>node_num = int(p.stdout.readline())
error:
Traceback (most recent call last):
  File "test_streamspot.py", line 246, in <module>
    main()
  File "test_streamspot.py", line 208, in main
    node_num = int(p.stdout.readline())
ValueError: invalid literal for int() with base 10: b''

Why does this error occur and how to solve this problem?

**Comment by 3arong** [comment]
切换到ROOT/threaTrace/graphchi-cpp-master/bin/example_apps/目录下，执行chmod 755 * 
我是这么解决的

**Comment by Lijuming33** [comment]
> 切换到ROOT/threaTrace/graphchi-cpp-master/bin/example_apps/目录下，执行chmod 755 * 我是这么解决的

哈哈，是我
